image:
  repository: "961906078703.dkr.ecr.eu-west-1.amazonaws.com/lesson-8-9-django-ecr"
  tag: "3"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

config:
  env:
    POSTGRES_PORT: "5432"
    POSTGRES_HOST: "db"
    POSTGRES_USER: "django_user"
    POSTGRES_DB: "django_db"
    POSTGRES_PASSWORD: "pass9764gd"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
